# config.yaml
program: fs_mol/qprobe_hpo.py
method: grid
name: sweep
metric:
  goal: maximize
  name: mean_best_aucpr
parameters:
  backbone:
    values: ["backbone_pretrained_models/1024-512.pt"]
  temperature:
    values: [1,2,3]
  lmbd_maha:
    values: [0.1,0.2,0.3,0.4,0.5]
  opt_cov:
    values: [false]
  optimizer_config__learning_rate:
    values: [0.001]

command:
  - python
  - ${program}
  - --train-sizes
  - [256,512]
  - --fold
  - VALIDATION