name: 'neuralsim'
encoder:
  activation: selu
  input_dim: 2248
  number_hidden_layers: 2
  number_hidden_neurons: 1024
  regularization:
    input_dropout: 0.1
    dropout: 0.5
layerNormBlock:
  usage: True
  affine: False
prediction_scaling: 0.044194173824159216
associationSpace_dim: 512
similarityModule:
  type: cosineSim
  l2Norm: False
  scaling: 1/sqrt(N)
training:
  batch_size: 4096
  optimizer: AdamW
  lr: 0.1 # 0.001
  weightDecay: 0.
  lrScheduler:
    usage: True  # False